ALTER TABLE "Schema"."ENTITY1" DROP CONSTRAINT "ENTITY1_PK" CASCADE;

-- Renaming table to maintain a backup;

ALTER TABLE "Schema"."ENTITY1" RENAME TO "ENTITY1_BU0";

CREATE TABLE "Schema"."ENTITY1" (
		"ATTRIBUTE1" CHAR(5) NOT NULL,
		"ATTRIBUTE2" CHAR(5) NOT NULL,
		"ATTRIBUTE3" CHAR(5) NOT NULL,
		"ATTRIBUTE4" CHAR(5),
		"ATTRIBUTE5" CHAR(5)
	)
	DISTRIBUTE ON RANDOM;

ALTER TABLE "Schema"."ENTITY1" ADD CONSTRAINT "ENTITY1_PK" PRIMARY KEY
	("ATTRIBUTE1",
	 "ATTRIBUTE2",
	 "ATTRIBUTE3");

